export enum TerrainType {
    Water = 0,
    Grass = 1,
    Hills = 2,
    Mountain = 3,
    Desert = 4,
    Snow = 5,
    Tundra = 7,
    Djungle = 8,
    Plains = 9,
    GrassHills = 10,
    SaltLake = 11,
    IceFloe = 12,
    DjungleHills = 13,
    HighMountain = 14,
    SnowMountain = 15,
    Lava = 16,
    AshPlains = 17,
    AshHills = 18,
}