export enum TerrainType {
    Water = 'Water',
    Grass = 'Grass',
    Hills = 'Hills',
    Mountain = 'Mountain',
    Desert = 'Desert',
    Snow = 'Snow',
    Tundra = 'Tundra',
    Djungle = 'Djungle',
    Plains = 'Plains',
    GrassHills = 'GrassHills',
    SaltLake = 'SaltLake',
    IceFloe = 'IceFloe',
    DjungleHills = 'DjungleHills',
    HighMountain = 'HighMountain',
    SnowMountain = 'SnowMountain',
    Lava = 'Lava',
    AshPlains = 'AshPlains',
    AshHills = 'AshHills',
}
